---
- name: Build Docker images from Dockerfiles.
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    path: "/vagrant/services/docker/{{ item.directory }}"
    state: build
  with_items:
    - { name: data, tag: "data", directory: data }
    - { name: www, tag: "flask", directory: www }
    - { name: db, tag: mysql, directory: db }

# Data containers don't need to be running to be utilized.
- name: Run a Data container.
  docker_container:
    image: data:data
    name: data
    state: present

- name: Run a Flask container.
  docker_container:
    image: www:flask
    name: www
    state: started
    command: python /opt/www/index.py
    ports: "80:80"

- name: Run a MySQL container.
  docker_container:
    image: db:mysql
    name: db
    state: started
    volumes_from: data
    ports: "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
