# This box will serve as the storage volume for the other apps
FROM busybox
MAINTAINER John Rizzo <johnrizzo1@gmail.com

# Create data volume for MySQL.
RUN mkdir -p /var/lib/mysql
VOLUME /var/lib/mysql
